package wikisum;
import java.awt.*;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;
import javax.swing.JOptionPane;


/**
 *
 * @author Ayush Verma
 */
public class Main extends javax.swing.JFrame {

    //Intializing
    int ch=-1;
    //ch=0 Online
    //ch=1 Offline
    //ch=-1 Initial value
   
    int type=1;
    
    String subVal="ALL";
    
    
    public Main() {
        initComponents();
        
        
        //Intialize
        //Set everthing invisible
        wikiLabel.setVisible(false);
        input.setVisible(false);
        catLabel.setVisible(false);
        catChoice.setVisible(false);
        lengthLabel.setVisible(false);
        length.setVisible(false);
        sum.setVisible(false);
        jScrollPane2.setVisible(false);
        subCat.setVisible(false);
        subCatLabel.setVisible(false);
        catDisp.setVisible(false);
        subCatDisp.setVisible(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        out = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame2 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        sum = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        wikiLabel = new javax.swing.JLabel();
        catLabel = new javax.swing.JLabel();
        subCatLabel = new javax.swing.JLabel();
        subCat = new javax.swing.JComboBox<>();
        catChoice = new javax.swing.JComboBox<>();
        input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        on = new javax.swing.JRadioButton();
        off = new javax.swing.JRadioButton();
        lengthLabel = new javax.swing.JLabel();
        length = new javax.swing.JTextField();
        catDisp = new javax.swing.JLabel();
        subCatDisp = new javax.swing.JLabel();

        jFrame1.setTitle("Summary");
        jFrame1.setBackground(new java.awt.Color(51, 51, 51));
        jFrame1.setMinimumSize(new java.awt.Dimension(1000, 750));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Summary");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("-----------------------------------");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("Mode:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("--------");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("No. of Lines: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("Type: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("--------");

        edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit ");
        edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        edit.setContentAreaFilled(false);
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        save.setContentAreaFilled(false);
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("Title: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("--------");

        out.setEditable(false);
        out.setBackground(new java.awt.Color(102, 102, 102));
        out.setColumns(20);
        out.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        out.setForeground(new java.awt.Color(255, 255, 255));
        out.setLineWrap(true);
        out.setRows(5);
        out.setWrapStyleWord(true);
        out.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(out);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(372, 372, 372)
                                        .addComponent(jLabel7)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(438, 438, 438)
                                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(3, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame2.setBackground(new java.awt.Color(0, 0, 0));
        jFrame2.setSize(new java.awt.Dimension(550, 480));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(550, 480));
        jPanel3.setName(""); // NOI18N
        jPanel3.setRequestFocusEnabled(false);

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.gif"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LOADING");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continue");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WikiSum 2.1");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(830, 650));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(null);

        inputArea.setBackground(new java.awt.Color(153, 153, 153));
        inputArea.setColumns(20);
        inputArea.setLineWrap(true);
        inputArea.setRows(5);
        inputArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(inputArea);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 280, 760, 260);

        sum.setBackground(new java.awt.Color(102, 102, 102));
        sum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sum.setForeground(new java.awt.Color(255, 255, 255));
        sum.setText("Summarize Now");
        sum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        sum.setContentAreaFilled(false);
        sum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sumMouseExited(evt);
            }
        });
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        jPanel1.add(sum);
        sum.setBounds(320, 550, 210, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Source");
        jLabel6.setToolTipText("Select the source for summary");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 60, 90, 30);

        wikiLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wikiLabel.setForeground(new java.awt.Color(255, 255, 255));
        wikiLabel.setText("URL:");
        wikiLabel.setToolTipText("Select the Wekipedia Page. You can enter any other webpage but it is optimised for Wikipedia only");
        jPanel1.add(wikiLabel);
        wikiLabel.setBounds(30, 110, 90, 30);

        catLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        catLabel.setForeground(new java.awt.Color(255, 255, 255));
        catLabel.setText("Category");
        jPanel1.add(catLabel);
        catLabel.setBounds(30, 160, 130, 40);

        subCatLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subCatLabel.setForeground(new java.awt.Color(255, 255, 255));
        subCatLabel.setText("Sub Category:");
        jPanel1.add(subCatLabel);
        subCatLabel.setBounds(30, 230, 140, 20);

        subCat.setBackground(new java.awt.Color(255, 204, 51));
        subCat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Here" }));
        subCat.setToolTipText("Select an Item from the drop down menu");
        subCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCatActionPerformed(evt);
            }
        });
        jPanel1.add(subCat);
        subCat.setBounds(190, 223, 160, 30);

        catChoice.setBackground(new java.awt.Color(255, 204, 51));
        catChoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        catChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Here", "Country", "Place", "People", "Scientific", "Others" }));
        catChoice.setToolTipText("Select an Item from the drop down menu");
        catChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catChoice.setNextFocusableComponent(subCat);
        catChoice.setOpaque(false);
        catChoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catChoiceMouseClicked(evt);
            }
        });
        catChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catChoiceActionPerformed(evt);
            }
        });
        jPanel1.add(catChoice);
        catChoice.setBounds(190, 170, 160, 30);

        input.setBackground(new java.awt.Color(204, 204, 204));
        input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input.setText("https://en.wikipedia.org/wiki/India");
        input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputMouseClicked(evt);
            }
        });
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        jPanel1.add(input);
        input.setBounds(140, 110, 640, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("WikiSum 2.1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(323, 13, 151, 29);

        on.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(on);
        on.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        on.setForeground(new java.awt.Color(51, 204, 0));
        on.setText("Online (Recomended)");
        on.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onMouseExited(evt);
            }
        });
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });
        jPanel1.add(on);
        on.setBounds(140, 60, 290, 30);

        off.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(off);
        off.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        off.setForeground(new java.awt.Color(51, 204, 0));
        off.setText("Offline");
        off.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                offMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                offMouseExited(evt);
            }
        });
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });
        jPanel1.add(off);
        off.setBounds(440, 60, 210, 30);

        lengthLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lengthLabel.setForeground(new java.awt.Color(255, 255, 255));
        lengthLabel.setText("Summary Size");
        lengthLabel.setToolTipText("Maximum length of the desired summary in Lines.");
        jPanel1.add(lengthLabel);
        lengthLabel.setBounds(540, 220, 150, 30);

        length.setBackground(new java.awt.Color(204, 204, 204));
        length.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        length.setText("12");
        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });
        jPanel1.add(length);
        length.setBounds(701, 221, 80, 30);
        jPanel1.add(catDisp);
        catDisp.setBounds(370, 160, 40, 50);

        subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question.png"))); // NOI18N
        jPanel1.add(subCatDisp);
        subCatDisp.setBounds(370, 220, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
        //if(input.)
    }//GEN-LAST:event_inputActionPerformed

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthActionPerformed
    //Formating Text Pre Processing
    public String[] formatText(String givenText)
    {   
        String text1=givenText.replace(". ",".BREAK");
        text1 = text1.replaceAll("\\[.*?\\]","");
        String text2=text1.replace(". ",".BREAK");
        String[] data=text2.split("BREAK");
        
        return data;
    }
    
    //For Education Class
    public void Education(String[] data, int len)
    {
        String resArr[]=new String[data.length];
        
        for(int i=1,j=1,k=0;i<data.length;i++) 
        {
           if(data[i].length()<200&data[i].length()>70)
           {
               if(data[i].matches("(.*)educatio(.*)")||data[i].matches("(.*)universit(.*)")||data[i].matches("(.*)college(.*)")||data[i].matches("(.*)degree(.*)")||data[i].matches("(.*)school(.*)"))
               {
                   resArr[k]=j+". "+data[i];
                   k++;
                   j++;
                }
           }
        }
        for (int i=0;i<len;i++)
        {
            if(resArr[i]==(null)) //can't use .equals
            {
                break;
            }
            out.append(resArr[i]+"\n");
        }
    }
    //For Cluture Class
    public void Culture(String[] data, int len)
    {
        String resArr[]=new String[data.length];
        
        for(int i=1,j=1,k=0;i<data.length;i++) 
        {
           if(data[i].length()<200&data[i].length()>70)
           {
               if(data[i].matches("(.*)entertainment(.*)")||data[i].matches("(.*)film(.*)")||data[i].matches("(.*)music(.*)")||data[i].matches("(.*)radio(.*)")||data[i].matches("(.*)news(.*)"))
                {
                   resArr[k]=j+". "+data[i];
                   k++;
                   j++;
                }
           }
          
        }
        for (int i=0;i<len;i++)
        {
            if(resArr[i]==(null)) //can't use .equals
            {
                break;
            }
            out.append(resArr[i]+"\n");
        }
       
    }
    //For Economy Class
    public void Economy(String[] data, int len,String title) 
    {
        String resArr[]=new String[data.length];
        
        for(int i=1,j=1,k=0;i<data.length;i++) 
        {
           if(data[i].length()<200&data[i].length()>70)
           {
               if(data[i].matches("(.*)GDP\\s(.*)")||data[i].matches("(.*)financ(.*)")||data[i].matches("(.*)industr(.*)")||data[i].matches("(.*)sector(.*)"))
                {
                   resArr[k]=j+". "+data[i];
                   k++;
                   j++;
                }
           }
          
        }
        for (int i=0;i<len;i++)
        {
            if(resArr[i]==(null)) //can't use .equals
            {
                break;
            }
            out.append(resArr[i]+"\n");
        }
        
    }
   //For Weather Class
    public void Weather(String[] data, int len)
    {
        String resArr[]=new String[data.length];
        
        for(int i=1,j=1,k=0;i<data.length;i++) 
        {
           if(data[i].length()<200&data[i].length()>70)
           {
                if(data[i].matches("(.*)temperature(.*)")||data[i].matches("(.*)climat(.*)")||data[i].matches("(.*)°C(.*)"))
               {
                   resArr[k]=j+". "+data[i];
                   k++;
                   j++;
                }
           }
          
        }
        for (int i=0;i<len;i++)
        {
            if(resArr[i]==(null)) //can't use .equals
            {
                break;
            }
            out.append(resArr[i]+"\n");
        }
    }
     //For Demographics Class
    public void Demographics(String[] data, int len)
    {
        String resArr[]=new String[data.length];
        
        for(int i=1,j=1,k=0;i<data.length;i++) 
        {
           if(data[i].length()<200&data[i].length()>70)
           {
               if(data[i].matches("(.*)popul(.*)")||data[i].matches("(.*)litera(.*)")||data[i].matches("(.*)ethinic(.*)"))
               {
                   resArr[k]=j+". "+data[i];
                   k++;
                   j++;
                }
           }
          
//          jLabel10.setText(""+(j-1)); //changes everytime 
        }
        for (int i=0;i<len;i++)
        {
            if(resArr[i]==(null)) //can't use .equals
            {
                break;
            }
            out.append(resArr[i]+"\n");
        }
    }
     //For Early life Class
   public void EarlyLife(String[] data, int len)
    {   
        String resArr[]=new String[data.length];
        
        for(int i=1,j=1,k=0;i<data.length;i++) 
        {
           if(data[i].length()<200&data[i].length()>70)
           {  
              if(data[i].matches("(.*)born(.*)")||data[i].matches("(.*)family(.*)")||data[i].matches("(.*)children(.*)")||data[i].matches("(.*)father(.*)")||data[i].matches("(.*)mother(.*)")||data[i].matches("(.*)wife(.*)"))
              {
                   resArr[k]=j+". "+data[i];
                   k++;
                   j++;
                }
           }
        }
        for (int i=0;i<len;i++)
        {
            if(resArr[i]==(null)) //can't use .equals
            {
                break;
            }
            out.append(resArr[i]+"\n");
        }
    }
    //For general purpose 
    public void ALL(String[] data, int len)
    { 
        //String resArr[]=new String[data.length];
        
        ArrayList <String> d= new ArrayList<>();
        ArrayList <String> sd= new ArrayList<>();
        out.append("1. "+data[0]);
        
        for(int i=1,j=1,k=0;i<data.length;i++) 
        {
           if(data[i].length()<200&data[i].length()>70)
           {  
              if(data[i].matches("(.*)est\\s(.*)")||data[i].matches(".*\\d+.*"))
                {
                   d.add(data[i]);
                   //resArr[k]=j+". "+data[i];
                   k++;
                   j++;
                }
           }
          
        }
        for(int i=0;i<d.size();i++)
        {
            if(d.get(i).matches("(.*)est\\s(.*)")&d.get(i).matches(".*\\d+.*"))
            {
                sd.add(d.get(i));
                d.remove(i);
            }
        }

        for(int i=0;i<sd.size();i++)
        {
            d.add(i,sd.get(i));
        }
        
        for (int i=0;i<d.size();i++)
        {
           if(i>(len-2))
           {
               break;
           }
           else
            out.append("\n"+(i+2)+". "+d.get(i));
        }
        
    }
    //Formula section
    
    public void Formula(String[] data, int len)
    {   
        out.append("\\begin{document} \n {\\displaystyle \\underline { Formula Sheet: "+jLabel13.getText()+"}} \\newline \n");
        for(int i=1,j=1;i<data.length;i++) 
        {
           if(data[i].length()<200)
           {
               //if(data[i].matches("(.*)est\\s(.*)")&&data[i].matches(".*\\d+.*"))
               //if(data[i].matches("(.*)llion\\s(.*)")&&data[i].matches(".*\\d+.*"))
                {
                   
                   out.append("=> {\\displaystyle "+data[i]+"\\newline"+"\n");
                  System.out.println("=> {\\displaystyle "+data[i]+"\\newline"+"\n");    
                   j++;
                   //c=j;
                }
           }
           //jLabel10.setText(""+(j-1));
        }
        out.append("\\end{document}");
    }
    
    
    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep(); 
        jFrame2.setVisible(true);
        int len= Integer.parseInt(length.getText());
        String title="Document";
        //System.out.println("ch: "+ch);
        
        
        //Online
        if(ch==0)
        {
            String request=input.getText();
            if(request.isEmpty())
            {
                JOptionPane.showMessageDialog(input,"Enter the web address","ERROR",JOptionPane.ERROR_MESSAGE);
                jFrame2.setVisible(false);
            }
            else
            {   
                
                //else
                {      
                    //System.out.println(catChoice.getSelectedItem().toString());
                    //Input raw data from Wikipedia
                    Document doc = null;
                        try 
                        {
                            doc = Jsoup.connect(request).get();
                        } 
                        catch (IOException ex) 
                        {

                            JOptionPane.showMessageDialog(this,"Unable to connect to Internet","ERROR",JOptionPane.ERROR_MESSAGE);
                            jFrame2.setVisible(false);

                        }

                    //Formating text
                    String text;
                    String[] data;
                    if(catChoice.getSelectedItem().equals("Scientific"))
                    {                        
                        Elements p= doc.select("annotation");
                        text = p.text();
                        
                        //System.out.print(text);
                        
                        String text1=text.replace("{\\displaystyle", "BREAK");
                        //String text2=text1.replace(".\\", "");
                        //String text3=text2.replace(",}", "BREAK");
                        
                        
                        data=text1.split("BREAK");
                        //System.out.println(Arrays.toString(data));
                        subVal="Formulas Only";
                    }
                    else
                    {
                        Elements p= doc.select("p");
                        text = p.text(); 
                        data = formatText(text);
                    }

                   

                    //Title
                    String titleRaw = doc.title();
                    title=titleRaw.replace("- Wikipedia", "");
                    jLabel13.setText(title);

                    //Other information
                    jLabel8.setText(""+data.length);
                    String[] titleData=null;
                    //int imp=0;


                    //Displaying Results
                    out.removeAll();
                    out.setText("");
                    jLabel11.setText(""+type);
                    
                    ////////////////////////////////////
                    

                    /////////////////////////////////////
                    
                    if(subVal.equals("Economy"))
                    {
                       
                            Economy(data,len,title);
                        
                    }

                    if(subVal.equals("Demographics"))
                    {
                      Demographics(data,len);  
                    }

                    if(subVal.equals("Weather"))
                    {
                      Weather(data,len); 
                    }

                    if(subVal.equals("Education"))
                    {
                       Education(data,len);                   
                    }

                    if(subVal.equals("Culture"))
                    {
                       Culture(data,len);   
                    }

                    if(subVal.equals("ALL"))
                    {
                        ALL(data,len);
                    }

                    if(subVal.equals("Early Life"))
                    {
                        EarlyLife(data,len);
                    }
                    
                    if(subVal.equals("Formulas Only"))
                    {
                        Formula(data,len);
                    }
                    
                }
                
                //jFrame1.setVisible(true);
                jLabel11.setText(catChoice.getSelectedItem().toString()+" : "+ subCat.getSelectedItem().toString());
                jLabel9.setText("Online");
            }
        }
        //Offline
        else if(ch==1)
        {
            //Intialization
            //jLabel12.setVisible(false);
            //jLabel13.setVisible(false);
            jLabel13.setText(title);
            
            //Input data and create an array
            String text=inputArea.getText();
            //System.out.println("---------------------------------");
            //System.out.println(text);
            
            //Formating data
            String text1=text.replace(". ",".BREAK");
            //System.out.println("---------------------------------");
            //System.out.println(text);
            //text1 = text1.replaceAll("\\[.*?\\]","");
            String text2=text1.replace(". ",".BREAK");
            String text3=text2.replace(".   ",".BREAK");
            String[] data=text2.split("BREAK");
            //System.out.println("---------------------------------");
            
        
        //return data;
            //String Data[]=formatText(text);
            
            //If users enters no data
            if(inputArea.getText().equals(""))
            {
             JOptionPane.showMessageDialog(this,"Enter the Data","ERROR",JOptionPane.ERROR_MESSAGE);
             jFrame2.setVisible(false);
             
            }
            //Else data is present
            else if(data.length<=1)
            {
                JOptionPane.showMessageDialog(this,"Data is too short","ERROR",JOptionPane.ERROR_MESSAGE);
                jFrame2.setVisible(false);
            }
            else
            {
                //Print Other Information
                out.removeAll();
                out.setText("");
                jLabel8.setText(""+data.length);
                
                
                //Print Data
                out.append("1. "+data[0]);
                
                for(int i=1;i<data.length;i++)
                {
                   
                    out.append("\n"+i+">>"+data[i].trim());
                    //out.append(res.replaceAll(i+". "+"\\s+", " "));
                }

                    if(subVal.equals("Economy"))
                    {
                        Economy(data,len,title);
                    }

                    if(subVal.equals("Demographics"))
                    {
                      Demographics(data,len);  
                    }

                    if(subVal.equals("Weather"))
                    {
                      Weather(data,len); 
                    }

                    if(subVal.equals("Education"))
                    {
                       Education(data,len);                   
                    }

                    if(subVal.equals("Culture"))
                    {
                       Culture(data,len);   
                    }

                    if(subVal.equals("ALL"))
                    {
                        ALL(data,len);
                    }

                    if(subVal.equals("Early Life"))
                    {
                        EarlyLife(data,len);
                    }
                    
                    if(subVal.equals("Formulas Only"))
                    {
                        Formula(data,len);
                    }
                
                //jFrame1.setVisible(true);
                jLabel11.setText(catChoice.getSelectedItem().toString()+" : "+ subCat.getSelectedItem().toString());
                jLabel9.setText("Offline");
            }
        }
        
        //jFrame2.setVisible(false);
            
        
        
    }//GEN-LAST:event_sumActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        // TODO add your handling code here:
        if(on.isSelected())
        {
            //Make Visible
            wikiLabel.setVisible(true);
            input.setVisible(true);  
            catLabel.setVisible(true);
            catDisp.setVisible(true);
            catChoice.setVisible(true);
//            lengthLabel.setVisible(true);
//            length.setVisible(true);
            //sum.setVisible(true);
            
            //Make Invisible
            inputArea.setVisible(false);
            jScrollPane2.setVisible(false);
            
            //Choice
            ch=0;
        }
    }//GEN-LAST:event_onActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        // TODO add your handling code here:
        if(off.isSelected())
        {
            //Make Visible
            
            catLabel.setVisible(true);
            catDisp.setVisible(true);
            catChoice.setVisible(true);
            
            //sum.setVisible(true);
            
            //Make invisible
            wikiLabel.setVisible(false);
            input.setVisible(false);
            inputArea.setVisible(true);
          
            //Choice
            ch=1;
            
            
        }
    }//GEN-LAST:event_offActionPerformed

    private void catChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catChoiceActionPerformed
        // TODO add your handling code here:
        subCat.setVisible(true);
        subCatDisp.setVisible(true);
        
        subCatLabel.setVisible(true);
        if(ch==1)
        {
            inputArea.setVisible(true);
            jScrollPane2.setVisible(true);
        }
        lengthLabel.setVisible(true);
        length.setVisible(true);
        
        
        String val=catChoice.getSelectedItem().toString();
        //System.out.println("Selected Type: "+val);
        if(val.equals("Country"))
        {
            type=1;
            subCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL","Economy","Demographics","Culture"}));
            sum.setVisible(true);
            catDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/india.png"))); 
        }
        else if(val.equals("Place"))
        {
            type=2;
            subCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL","Economy","Demographics","Weather","Education"  }));
            sum.setVisible(true);
            catDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gate-of-india.png"))); 
        }
        else if(val.equals("People"))
        {
            type=3;
            subCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL","Early Life","Education" }));
            sum.setVisible(true);
            catDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man.png"))); 
        }
        else if(val.equals("Scientific"))
        {
            type=4;
            subCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Formulas Only"}));
            sum.setVisible(true);
            catDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student.png"))); 
        }
        else if(val.equals("Others"))
        {
            type=5;
            subCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL"}));
            sum.setVisible(true);
            catDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checked.png"))); 
        }
        else if(val.equals("Select Here"))
        {
            sum.setVisible(false);
            catDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); 
        }
        //System.out.println("Type: "+type);
        
                
        
    }//GEN-LAST:event_catChoiceActionPerformed

    private void subCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCatActionPerformed
        // TODO add your handling code here:
        
        subVal=subCat.getSelectedItem().toString();
        if(subVal.equals("Economy"))
                    {
                        subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rupee.png")));
                    }

                    if(subVal.equals("Demographics"))
                    {
                      subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/network.png"))); 
                    }

                    if(subVal.equals("Weather"))
                    {
                      subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sun.png"))); 
                    }

                    if(subVal.equals("Education"))
                    {
                       subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student.png")));               
                    }

                    if(subVal.equals("Culture"))
                    {
                       subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oil-lamp.png")));
                    }

                    if(subVal.equals("ALL"))
                    {
                        subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checked.png")));
                    }

                    if(subVal.equals("Early Life"))
                    {
                        subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blocks.png")));
                    }
                    
                    if(subVal.equals("Formulas Only"))
                    {
                       subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h2o.png")));
                    }
        //System.out.println("subval: "+subVal);
        
    }//GEN-LAST:event_subCatActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
       Toolkit.getDefaultToolkit().beep(); 
        out.setEditable(true);
    }//GEN-LAST:event_editActionPerformed

    private void onMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMouseEntered
        // TODO add your handling code here:
       on.setFont(new java.awt.Font("Tahoma", 1, 19)); 
    }//GEN-LAST:event_onMouseEntered

    private void onMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMouseExited
        // TODO add your handling code here:
        on.setFont(new java.awt.Font("Tahoma", 0, 18));
    }//GEN-LAST:event_onMouseExited

    private void offMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offMouseEntered
        // TODO add your handling code here:
        off.setFont(new java.awt.Font("Tahoma", 1, 19)); 
    }//GEN-LAST:event_offMouseEntered

    private void offMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offMouseExited
        // TODO add your handling code here:
        off.setFont(new java.awt.Font("Tahoma", 0, 18));
    }//GEN-LAST:event_offMouseExited

    private void inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputMouseClicked
        // TODO add your handling code here:
        //input.selectAll();
    }//GEN-LAST:event_inputMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep(); 
        String str= out.getText();
        
        String filename=jLabel13.getText();
        String suffix=subCat.getSelectedItem().toString();
        try {            
            BufferedWriter bf = new BufferedWriter ( new FileWriter(".\\"+filename+""+suffix+".rtf"));      
            BufferedWriter bfl = new BufferedWriter ( new FileWriter("./"+filename+""+suffix+".txt"));   
            bf.write(str);
            bf.close(); 
            bfl.write(str);
            bfl.close(); 
        } 
        catch (IOException ex) 
        {
            //Logger.getLogger(PDFexp.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "File Saved","Success",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_saveActionPerformed

    private void sumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumMouseEntered
        // TODO add your handling code here:
        sum.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        sum.setForeground(new java.awt.Color(0, 204, 0));
    }//GEN-LAST:event_sumMouseEntered

    private void sumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumMouseExited
        // TODO add your handling code here:
        sum.setFont(new java.awt.Font("Tahoma", 1, 18));
        sum.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_sumMouseExited

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        // TODO add your handling code here:
        save.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        save.setForeground(new java.awt.Color(0, 204, 0));
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        // TODO add your handling code here:
        save.setFont(new java.awt.Font("Tahoma", 1, 18));
        save.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_saveMouseExited

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        // TODO add your handling code here:
        edit.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        edit.setForeground(new java.awt.Color(0, 204, 0));
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
        // TODO add your handling code here:
        edit.setFont(new java.awt.Font("Tahoma", 1, 18));
        edit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_editMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep(); 
        jFrame2.setVisible(false);
        jFrame1.setVisible(true);
        if(subVal.equals("Formulas Only"))
        {
            JOptionPane.showMessageDialog(null, "You can Copy Paste this code in LaTeX editor to get the desired output","Pro Tip!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void catChoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catChoiceMouseClicked
        // TODO add your handling code here:
        subCatDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question.png")));
    }//GEN-LAST:event_catChoiceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> catChoice;
    private javax.swing.JLabel catDisp;
    private javax.swing.JLabel catLabel;
    private javax.swing.JButton edit;
    private javax.swing.JTextField input;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField length;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JRadioButton off;
    private javax.swing.JRadioButton on;
    private javax.swing.JTextArea out;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> subCat;
    private javax.swing.JLabel subCatDisp;
    private javax.swing.JLabel subCatLabel;
    private javax.swing.JButton sum;
    private javax.swing.JLabel wikiLabel;
    // End of variables declaration//GEN-END:variables
}
